import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { PostStore } from '../server/store.js';
import { createApi } from '../server/api.js';
const article = { id:'first-story',title:'First story',description:'A description',pubDate:'2026-09-08',draft:true,tags:['Notes'],body:'## Hello\n\nA **good** story.\n' };
async function setup(t: any) { const dir=await fs.mkdtemp(path.join(await fs.realpath(os.tmpdir()),'karma-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return {dir,store:new PostStore(dir)}; }
test('create, read, edit, list and delete a Markdown article',async t=>{const {store}=await setup(t);const created=await store.save(article,true);assert.equal(created.body,article.body);assert.equal((await store.list()).posts.length,1);const updated=await store.save({...created,title:'Revised'});assert.notEqual(updated.revision,created.revision);await store.remove(updated.id,updated.revision);assert.equal((await store.list()).posts.length,0);});
test('preserves unknown YAML fields, comments and untouched Markdown',async t=>{const {store,dir}=await setup(t);const raw='---\n# Keep this comment\ntitle: First story\ndescription: A description\npubDate: 2026-09-08\ndraft: true\ntags: [Notes]\nauthor: Ada\ncustom:\n  nested: yes\n---\n<custom>Untouched</custom>\n\n[^note]: a footnote\n';await fs.writeFile(path.join(dir,'first-story.md'),raw);const p=await store.get('first-story');await store.save(p);assert.equal(await fs.readFile(path.join(dir,'first-story.md'),'utf8'),raw);await store.save({...p,title:'New title'});const saved=await fs.readFile(path.join(dir,'first-story.md'),'utf8');assert.match(saved,/# Keep this comment/);assert.match(saved,/author: Ada/);assert.match(saved,/nested: yes/);assert.equal((await store.get(p.id)).body,p.body);});
test('rejects duplicate names, stale saves and stale deletes',async t=>{const {store}=await setup(t);const p=await store.save(article,true);await assert.rejects(store.save(article,true),/already exists/);await store.save({...p,title:'External update'});await assert.rejects(store.save({...p,title:'Stale'}),/changed/);await assert.rejects(store.remove(p.id,p.revision),/changed/);});
test('serializes competing saves',async t=>{const {store}=await setup(t);const p=await store.save(article,true);const results=await Promise.allSettled([store.save({...p,title:'One'}),store.save({...p,title:'Two'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
test('rejects traversal, symlinks, invalid dates and non-boolean drafts',async t=>{const {store,dir}=await setup(t);for(const id of ['../escape','/absolute','a/../../x','a\\b'])await assert.rejects(store.save({...article,id},true));await fs.symlink(path.join(dir,'outside.md'),path.join(dir,'linked.md'));await assert.rejects(store.get('linked'),/Symlink/);await assert.rejects(store.save({...article,pubDate:'2026-02-31'},true),/date/);await assert.rejects(store.save({...article,draft:'false'} as any,true),/status/);});
test('reports malformed files without hiding valid articles',async t=>{const {store,dir}=await setup(t);await store.save(article,true);await fs.writeFile(path.join(dir,'broken.md'),'---\ntitle: [\n---\nbody');const result=await store.list();assert.equal(result.posts.length,1);assert.equal(result.errors[0].id,'broken');});
test('API rejects foreign origins and hosts, requires JSON mutation header, and supports CRUD',async t=>{const {store}=await setup(t);const app=createApi(store,{contentDir:'test',mediaDir:'media',siteUrl:'http://localhost:4321'});const headers={'host':'localhost:4000','content-type':'application/json','x-karma-request':'1'};const req=(url:string,init?:RequestInit)=>app.request('http://localhost:4000'+url,{...init,headers:{...headers,...init?.headers}});assert.equal((await req('/api/posts',{headers:{origin:'https://evil.example'}})).status,403);assert.equal((await req('/api/posts',{headers:{host:'evil.example'}})).status,403);assert.equal((await req('/api/posts',{method:'POST',headers:{'x-karma-request':''},body:JSON.stringify(article)})).status,403);const created=await req('/api/posts',{method:'POST',body:JSON.stringify(article)});assert.equal(created.status,201);const p=await created.json();assert.equal((await req('/api/post',{method:'PUT',body:JSON.stringify({...p,title:'Changed'})})).status,200);assert.equal((await req('/api/post',{method:'DELETE',body:JSON.stringify(p)})).status,409);assert.equal((await req('/api/posts',{method:'POST',body:'{'})).status,400);});
