import { useEffect, useRef, useState } from 'react';
import { api } from '../lib/api';
import { ConfirmDialog } from './ConfirmDialog';
export interface MediaItem {name:string;url:string;alt:string;bytes:number;revision:string;metadataRevision:string;usedBy:string[]}
interface MediaList {items:MediaItem[];errors:{name:string;message:string}[];contentIssues:number}
export function MediaLibrary({onPick,onBusy=()=>{}}:{onPick?:(image:MediaItem)=>void;onBusy?:(busy:boolean)=>void}){
  const [data,setData]=useState<MediaList|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState<MediaItem|null>(null),[alt,setAlt]=useState(''),[deleting,setDeleting]=useState<MediaItem|null>(null),[uploadAlt,setUploadAlt]=useState('');
  const uploadInput=useRef<HTMLInputElement>(null);
  async function load(){const result=await api<MediaList>('/api/media');setData(result);return result;}
  useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
  async function run(operation:()=>Promise<void>){if(busy)return;setBusy(true);onBusy(true);setError('');setNotice('');try{await operation();}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy(false);}}
  async function upload(file:File){await run(async()=>{
    if(file.size>6*1024*1024)throw new Error('Choose an image smaller than 6 MB.');
    const encoded=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read the selected file.'));reader.readAsDataURL(file);});
    const item=await api<{name:string}>('/api/media','POST',{name:file.name,data:encoded,alt:uploadAlt});const result=await load();const image=result.items.find(i=>i.name===item.name)!;setSelected(image);setAlt(image.alt);setUploadAlt('');setNotice('Image uploaded.');
  });if(uploadInput.current)uploadInput.current.value='';}
  const visible=data?.items.filter(i=>(i.name+' '+i.alt).toLowerCase().includes(query.toLowerCase()))||[];
  return <div className="media-library" aria-busy={busy}>
    {error&&<div className="alert" role="alert">{error}<button disabled={busy} onClick={()=>void run(async()=>{await load();setSelected(null);})}>Reload media</button></div>}{notice&&<p role="status">{notice}</p>}
    <div className="media-upload"><label>Alt text for upload<input value={uploadAlt} maxLength={2000} disabled={busy} onChange={e=>setUploadAlt(e.target.value)} placeholder="Describe the image; leave blank if decorative"/></label><label className={`primary upload-label ${busy?'disabled':''}`}>{busy?'Working…':'Upload image'}<input ref={uploadInput} type="file" accept="image/png,image/jpeg,image/gif,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/></label></div><p className="field-help">PNG, JPEG, GIF or WebP · Up to 6 MB · Unique names prevent overwrites.</p>
    <label className="media-search">Find an image<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search filename or alt text…"/></label>
    {!data?<p role="status">{error?'Could not load media. Use Reload media to retry.':'Loading your images…'}</p>:<><div className="media-grid">{visible.map(item=><button className={`media-tile ${selected?.name===item.name?'selected':''}`} aria-pressed={selected?.name===item.name} key={item.name} disabled={busy} onClick={()=>{setSelected(item);setAlt(item.alt);}}><img loading="lazy" src={`/api/media/file?name=${encodeURIComponent(item.name)}&v=${item.revision}`} alt=""/><strong>{item.name}</strong><span>{Math.ceil(item.bytes/1024)} KB · {item.usedBy.length?`${item.usedBy.length} article(s)`:'No article references'}</span></button>)}</div>{!visible.length&&<div className="empty"><h3>{query?'No images found.':'Room for a little imagery.'}</h3><p>{query?'Try another filename or description.':'Upload your first image above.'}</p></div>}{data.errors.map(e=><p key={e.name} role="alert">{e.name}: {e.message}</p>)}{data.contentIssues>0&&<p role="alert">Some articles could not be read. Image deletion is disabled until they are fixed.</p>}</>}
    {selected&&<div className="media-details"><h3>{selected.name}</h3><code>{selected.url}</code><label>Image alt text<input value={alt} maxLength={2000} disabled={busy} onChange={e=>setAlt(e.target.value)}/></label><p className="field-help">Describe meaningful images. Leave blank for decorative images. Library alt text is copied when an image is inserted; existing articles keep their own alt text.</p>{selected.usedBy.length>0&&<p className="field-help">Used in: {selected.usedBy.join(', ')}</p>}<div className="dialog-actions"><button className="secondary" disabled={busy||alt===selected.alt} onClick={()=>void run(async()=>{await api('/api/media','PUT',{...selected,alt});const result=await load();setSelected(result.items.find(i=>i.name===selected.name)||null);setNotice('Alt text saved.');})}>Save alt text</button><button className="danger" disabled={busy||Boolean(selected.usedBy.length)||Boolean(data?.contentIssues)} onClick={()=>setDeleting(selected)}>Delete image</button>{onPick&&<button className="primary" disabled={busy} onClick={()=>onPick({...selected,alt})}>Use image</button>}</div><p className="field-help">Deletion checks this content collection. Check any uses in Astro pages or styles before deleting an image.</p></div>}
    {deleting&&<ConfirmDialog title="Delete this image?" busy={busy} onCancel={()=>setDeleting(null)} onConfirm={()=>void run(async()=>{await api('/api/media','DELETE',{name:deleting.name,revision:deleting.revision});setSelected(null);setDeleting(null);await load();setNotice('Image deleted.');})}><p>Permanently delete <strong>{deleting.name}</strong>? This cannot be undone. Confirm it is not used by other Astro files or collections.</p>{error&&<p className="dialog-error" role="alert">{error}</p>}</ConfirmDialog>}
  </div>;
}
export function MediaPage({onBusy}:{onBusy:(busy:boolean)=>void}){return <section className="content management-page"><p className="eyebrow">A PLACE FOR YOUR IMAGES</p><h1>Media library</h1><p className="subtitle">Upload, describe, and choose images for your stories.</p><MediaLibrary onBusy={onBusy}/></section>;}
export function MediaPicker({onPick,onClose}:{onPick:(image:MediaItem)=>void;onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>previous?.focus();},[]);
  return <dialog ref={ref} className="media-dialog" aria-labelledby="media-picker-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="media-dialog-heading"><h2 id="media-picker-title">Choose an image</h2><button className="secondary" autoFocus disabled={busy} onClick={onClose}>Close</button></div><MediaLibrary onPick={onPick} onBusy={setBusy}/></dialog>;
}
