import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { ConfirmDialog } from './ConfirmDialog';
export interface SettingsData {contentDir:string;mediaDir:string;siteUrl:string;previewPath:string}
export function SettingsPage({onSaved,onDirty,onBusy}:{onSaved:(data:SettingsData)=>void;onDirty:(dirty:boolean)=>void;onBusy:(busy:boolean)=>void}){
  const [saved,setSaved]=useState<{data:SettingsData;revision:string}|null>(null),[form,setForm]=useState<SettingsData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirming,setConfirming]=useState(false),[notice,setNotice]=useState('');
  const load=async()=>{try{const result=await api<NonNullable<typeof saved>>('/api/settings');setSaved(result);setForm(result.data);setError('');}catch(e){setError((e as Error).message);}};
  useEffect(()=>{void load();return()=>onDirty(false);},[]);
  const dirty=Boolean(form&&saved&&JSON.stringify(form)!==JSON.stringify(saved.data));
  useEffect(()=>{onDirty(dirty);},[dirty]);
  const change=(key:keyof SettingsData,value:string)=>setForm(p=>p?{...p,[key]:value}:p);
  async function save(){if(!form||!saved||busy)return;setBusy(true);onBusy(true);setError('');try{const result=await api<NonNullable<typeof saved>>('/api/settings','PUT',{data:form,revision:saved.revision});setSaved(result);setForm(result.data);setConfirming(false);setNotice('Settings saved and applied.');onSaved(result.data);}catch(e){setError((e as Error).message);}finally{setBusy(false);onBusy(false);}}
  return <section className="content management-page"><p className="eyebrow">YOUR WORKSPACE</p><h1>Simple by nature.</h1><p className="subtitle">Connect your writing space to your Astro project.</p>{error&&<div className="alert" role="alert">{error}<button disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved settings and reload?'))void load();}}>Reload settings</button></div>}{notice&&<p role="status">{notice}</p>}
    {!form?<p role="status">{error?'Settings unavailable. Reload to retry.':'Loading settings…'}</p>:<form className="settings-card settings-form" onSubmit={e=>{e.preventDefault();setConfirming(true);}}><fieldset disabled={busy}><label>Astro website URL<input type="url" required value={form.siteUrl} onChange={e=>change('siteUrl',e.target.value)}/></label><label>Article preview path<input required value={form.previewPath} onChange={e=>change('previewPath',e.target.value)} aria-describedby="preview-help"/></label><p id="preview-help" className="field-help">Use {'{slug}'} for the article slug, e.g. /blog/{'{slug}'}/. Saved drafts require the Astro development server.</p><label>Content directory<input required value={form.contentDir} onChange={e=>change('contentDir',e.target.value)}/></label><label>Media directory<input required value={form.mediaDir} onChange={e=>change('mediaDir',e.target.value)} aria-describedby="path-help"/></label><p id="path-help" className="field-help">Use existing repository-relative directories. Media must be inside public/. Switching paths does not move files or edit the Astro schema. Update Astro’s collection loader yourself if the content location changes.</p><div className="dialog-actions"><button className="secondary" type="button" disabled={!dirty} onClick={()=>setForm(saved!.data)}>Discard changes</button><button className="primary" disabled={!dirty}>{busy?'Saving…':'Save settings'}</button></div></fieldset><p>Overrides are saved in <code>cms.settings.json</code>. The original <code>cms.config.ts</code> stays intact.</p></form>}
    {confirming&&<ConfirmDialog title="Apply workspace settings?" busy={busy} onCancel={()=>setConfirming(false)} onConfirm={()=>void save()}><p>The CMS will switch to these paths immediately. Existing content and images stay where they are.</p><p><strong>Content:</strong> {form?.contentDir}<br/><strong>Media:</strong> {form?.mediaDir}<br/><strong>Preview:</strong> {form?.siteUrl}{form?.previewPath}</p>{error&&<p className="dialog-error" role="alert">{error}</p>}</ConfirmDialog>}
  </section>;
}
